parameters:
  name: gpt-basic-1m-64-emb-1L
  type: dense
  configuration:
    model:
      decoder_layers: 8
    decoder:
      input_dimension: 64
      output_dimension: 64
      hidden_dimension: 64
      experts: 8
      norm_eps: 1.0e-05
      attention:
        type: "multi-head"
        num_query_heads: 8
        num_kv_heads: 8
        embedding_dimension: 64
        head_dimension: 32
  tokenizer:
    config: configs/tokenizer/gpt-2.yaml
