parameters:
  experiment_name: "moe-language-modeling-tiny"
  epochs: 1000
  val_steps: 10
  checkpoint_frequency: 100
  batch_size: 8
  num_workers: 2
  sequence_length: 32
  lr: 0.001
  training_data_config: "configs/data/medium-corpus.yaml"
  validation_data_config: "configs/data/medium-corpus.yaml"
